# ─────────────────────────────────────────
#   KITTY CONFIG — tema: ultrarice
# ─────────────────────────────────────────

# ── Fonte ──
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ── Cursor ──
cursor                  #ff0000
cursor_text_color       #000000
cursor_shape            block
cursor_blink_interval   0.5
cursor_stop_blinking_after 0

# ── Janela ──
background_opacity       0.95
dynamic_background_color no
window_padding_width     12
confirm_os_window_close  0

# ── Cores base ──
foreground           #ffffff
background           #000000
selection_foreground #000000
selection_background #ff0000

# ── Borda ──
active_border_color   #ff0000
inactive_border_color #1a0000

# ── Paleta 16 cores ──
color0  #000000
color8  #2a0000

color1  #ff0000
color9  #ff3333

color2  #3a3a3a
color10 #5a5a5a

color3  #8b0000
color11 #cc0000

color4  #1a0000
color12 #2a0000

color5  #ff0000
color13 #ff3333

color6  #4a4a4a
color14 #888888

color7  #ffffff
color15 #ffffff

# ── URL ──
url_color #ff0000
url_style curly

# ── Tabs ──
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_background          #000000
active_tab_foreground       #000000
active_tab_background       #ff0000
active_tab_font_style       bold
inactive_tab_foreground     #8b0000
inactive_tab_background     #0a0000
inactive_tab_font_style     normal

# ── Bell ──
enable_audio_bell no
