wallpaper {
    monitor = HDMI-A-1
    path = /home/tc34b/.config/themes/gray_minim/wallpaper-hdmi.png
    fit_mode = cover
}


wallpaper {
    monitor = eDP-1
    path = /home/tc34b/.config/themes/gray_minim/wallpaper-edp.png
    fit_mode = cover
}

splash = false
ipc = on
